### ISSUE TITLE
TestUp Window Blank

### ISSUE THREAD

**Issue by Achill113** [SketchUp/testup-2#102]
When I open the TestUp Window it comes up completely blank. The Ruby Console does say "Reloaded 21 files!
MiniTest TestUp Extension discovered..." if I reload which tells me it does see the tests. Am I using this wrong or is there a bug?

**Comment by thomthom** [comment]
Can you include more info about your environment please?

* SketchUp version (Full version number)
* OS
* What version of IE/Safari is installed
* What version of TestUp? (From Extension Warehouse or from GitHub source?)

**Comment by Achill113** [comment]
Windows 10, SketchUp Pro 17.2.2555, IE version 11.192.16299.0, TestUp version 2.2.0

**Comment by Achill113** [comment]
[testup-2.zip](https://github.com/SketchUp/testup-2/files/1653470/testup-2.zip)
![testup](https://user-images.githubusercontent.com/10748096/35242614-04bbba64-ff88-11e7-8e4a-f4ecd0d79e10.PNG)

**Comment by Achill113** [comment]
SKUI was not included when I cloned the repo so I downloaded it directly from your SKUI repo

**Comment by thomthom** [comment]
> SKUI was not included when I cloned the repo so I downloaded it directly from your SKUI repo

@Achill113 - SKUI is referenced as a sub-repo. When cloning TestUp you must make sure to also clone the sub-repos. Most git GUI clients will do this automatically, but if you use the command line you must add some additional parameters.
