### ISSUE TITLE
Adapter to switch between `UI::WebDialog` and `UI:HtmlDialog`

### ISSUE THREAD

**Issue by thomthom** [SketchUp/testup-2#111]
In order to run in SketchUp older than SU2017, useful to investigate regression history, TestUp need to remain compatible with `UI::WebDialog`. However, `UI::HtmlDialog` is much better for debugging while developing.

Create adapters that provide a common interface to both dialog classes which allows TestUp to switch between implementation. Allow for easy configuration switch as it's convenient to keep using the same SU version for testing both variants.

**Comment by Aerilius** [comment]
Just as a hint, the Bridge in Ruby Console+ has adapters for both. For js→rb they either use `window.sketchup['callbackName']` or `webdialog.get_element_value`. Because of HtmlDialog's asynchronicity both have async APIs.

**Comment by thomthom** [comment]
Thanks. I will look into that.
