### ISSUE TITLE
Revamp dialogs with a consistent "SketchUp" style

### ISSUE THREAD

**Issue by thomthom** [SketchUp/testup-2#112]
The current UI appearance stems from the original TestUp mixed with SKUI.

Create a consistent UI theme to be used for all dialogs. Consider getting rid of SKUI.

**Comment by Eneroth3** [comment]
Maybe the styling module of [Dialogs ](https://github.com/Eneroth3/dialogs)could be useful for this?

**Comment by thomthom** [comment]
@Eneroth3 did you pull the colors from Extension Manager?

**Comment by Eneroth3** [comment]
@thomthom Yup. And the bluish outline of the selected button (very useful when using Tab to cycle buttons) uses the Trimble blue.

**Comment by thomthom** [comment]
I'm not sure the EM colors are 100% up to date. I need to check with the UI/UX team. This was all a moving target when EM was developed.

Which reminds me - we should have some color style guide available to developers. 💡
