### ISSUE TITLE
Update toolbar icons with high DPI vector icons

### ISSUE THREAD

**Issue by thomthom** [SketchUp/testup-2#113]
Check with UI/UX team for possibiolity of existing set of Trimble/SketchUp style icons that can be used.

**Comment by Eneroth3** [comment]
It seems the main UI is moving towards trendy monochrome icons. I'd very much stay with colorful, easy to find icons if possible. Usability > trends.

**Comment by thomthom** [comment]
e1c97d5487b81b3cdeba498040f190b0f9b15e56
