### ISSUE TITLE
Forward JS errors to Ruby

### ISSUE THREAD

**Issue by thomthom** [SketchUp/testup-2#119]
See if uncaught JS errors can be forwarded to Ruby console.

**Comment by MSP-Greg** [comment]
Long time ago I used `window.onerror` to do so.

**Comment by Aerilius** [comment]
It's best to catch all and forward what you cannot handle. `window.onerror` has often empty parameters, but I think in FF and Webkit you get now the original error object as last parameter, including stack. I had to deal with it also in my Console+.

**Comment by thomthom** [comment]
Yea, I've caught errors before, I used something like this:

```ruby
window.onerror = function(message, file, line, column, error) {
  try
  {
    // Not all browsers pass along the error object. Without that it's not
    // possible to get full backtrace.
    // http://blog.bugsnag.com/js-stacktraces
    var backtrace = [];
    if (error && error.stack)
    {
      backtrace = String(error.stack).split("\n");
    }
    else
    {
      backtrace = [file + ':' + line + ':' + column];
    }
    var data = {
      'message' : message,
      'backtrace' : backtrace,
      'user-agent': navigator.userAgent,
      'document-mode': document.documentMode
    };
    Sketchup.callback('Window.js_error', data);
  }
  catch (error)
  {
    debugger;
    throw error;
  }
};
```

As Andreas mentions, not all browsers hand over the backtrace. For one project where I used Vue I assigned my own custom error handler that would give me nice backtraces. I left `window.onerror` in place as a fallback.

```js
Vue.config.errorHandler = sketchupErrorHandler;
```

I'm currently hooking refactoring the TestUp dialogs with Vue so I'll probably use the same approach.
