### ISSUE TITLE
TestUp-2.3.0 clicking on Preferences icon crashes SketchUp on Mac

### ISSUE THREAD

**Issue by hilliard-sketchup** [SketchUp/testup-2#156]
I was going to edit the file locations to use the SketchUp API Ruby dir in the client repository, I clicked on the preferences icon and the Application crashes, there is a bug splat. 

https://app.bugsplat.com/individualCrash/?id=445&database=SU19Mac

**Comment by thomthom** [comment]
Logged crash as SU-40706
