### ISSUE TITLE
TestUp-2.3.0 displays LayOut ruby tests, but cannot run them

### ISSUE THREAD

**Issue by hilliard-sketchup** [SketchUp/testup-2#157]
Tests like TC_LayOut_AngularDimension are listed in the run list but have the blue question mark that indicates not runnable. 
The path for these files are: 
/client/sketchup/source/layout/ruby/ruby_tests/run_ruby_tests.rb
The path for the Sketchup files (that are runnable)  is: 
/client/sketchup/source/sketchup/ruby/tests/SketchUp Ruby API/
The base class for the LayOut Ruby tests is MiniTest::Test not TestUp::Testcase

**Comment by thomthom** [comment]
Tests that doesn't inherit from the TestUp testcase isn't expected to run/load.
