### ISSUE TITLE
Hi，Sir, where could I find some more detailed instruction about it.

### ISSUE THREAD

**Issue by renchiyuan** [SketchUp/testup-2#164]
Hi，Sir, where could I find some more detailed instruction about how to run it.

I downloaded it, and followed all the steps. But it cant run in my rubymine yet. If I try to debug testup.rb, it always says wrong， such as "C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- testup/core (LoadError)", though I have added the path to the load path. So I have to modify all the filename like "testup/core" to "./testup/core". But after it, I encounter other errors. Could you send me a runnable project for rubymine about it. I use Sketchup 2017, rubymine 2018, ruby 2.5. My email is renchiyuan@gmail.com. Thanks very much. Merry Chrismas, Jerry

**Comment by renchiyuan** [comment]
erroes like this: 0> Sketchup.get_locale
=> uninitialized constant LanguageHandler::Sketchup

**Comment by Aerilius** [comment]
I would guess from the error that if `Sketchup` is not defined, maybe SketchUp is what you need?

- Have you downloaded and installed SketchUp? https://www.sketchup.com/download/all
- Are you running testup in SketchUp?
- If you intend to debug SketchUp extensions in Rubymine, you must run them through SketchUp ([set up SketchUp debugger](https://github.com/SketchUp/sketchup-ruby-api-tutorials/wiki/RubyMine-Debugger-Setup)), never with a stand-alone Ruby interpreter that does not know what Sketchup is.

**Comment by thomthom** [comment]
Can you elaborate on what you mean by "But it cant run in my rubymine yet. "?

Do you mean to debug in  RubyMine?
