### ISSUE TITLE
Number of passed tests can't refresh after run tests

### ISSUE THREAD

**Issue by linying1991** [SketchUp/testup-2#166]
testup version：Version 2.3.1.rbz
![image](https://user-images.githubusercontent.com/38310238/58410430-c6cfa680-80a4-11e9-8a42-aa7b7bced5bf.png)

**Comment by thomthom** [comment]
Do you have "Run in Console" checked?
![image](https://user-images.githubusercontent.com/192418/58424588-017f1200-8098-11e9-9cff-d4aeff1dff74.png)

If that's the case then the webdialog doesn't update with results.

**Comment by Eneroth3** [comment]
It would make sense that such button grays out the or otherwise hides the content of the dialog, and add a message describing why.

**Comment by linying1991** [comment]
this is my settings.
![image](https://user-images.githubusercontent.com/38310238/58443979-4488c600-8128-11e9-8bd3-92b1aa923287.png)

**Comment by thomthom** [comment]
@linying1991 what version of SketchUp are you using?

**Comment by linying1991** [comment]
@thomthom 
SketchUp: 19.0.685
    Ruby: 2.5.1
  TestUp: 2.3.1
Minitest: 5.11.3

Platform: platform_win
  Locale: zh-CN

**Comment by thomthom** [comment]
This is strange...

hmm.. @Eneroth3 - are you using the latest TestUp? Does it work for you? (Wondering if there's something on my development machine that cause me not to see the issue.)

**Comment by Eneroth3** [comment]
I'm on TestUp 2.2.0, with the old UI.

**Comment by thomthom** [comment]
@linying1991 - are you able to test v 2.2? If that works it would give us some clues to start working off.

**Comment by linying1991** [comment]
@thomthom I think I've found the reason. Before installing Testup2, I installed Minitest-5.11.3.

Now, i uninstall Minitest-5.11.3, Testup2 works normally.
thanks very mush~~~
![image](https://user-images.githubusercontent.com/38310238/58742201-60a4a400-8455-11e9-9505-276845e3b27c.png)

**Comment by linying1991** [comment]
@thomthom v2.2 can't work on my computer...

**Comment by thomthom** [comment]
> Before installing Testup2, I installed Minitest-5.11.3.

Ah! That's interesting. TestUp bundles 5.4.3 within the RBZ to allow it to be installed without internet connection or have the lag it takes to download and install.

I wonder if I can make it try to load that specific version... However, I guess we'd also run into issues if a newer version was loaded before TestUp. So maybe we need a detection in place to inform the user of a clash.

I'm reopening this issue for that purpose.

That you for your report and investigation.
