### ISSUE TITLE
Tests are not discovered

### ISSUE THREAD

**Issue by anuragaj** [SketchUp/testup-2#188]
I am trying to use TestUp to run some of the tests I am planning to write for SketchUp-ruby interaction for an extension.
But the TestUp window doesn't discover the tests I have. 
- added path to my tests in TestUp window->Add.
- I do not see my tests in the window.
- When I click re-run... and select my test file I get the following error in the ruby console
```
Error: #<JSON::ParserError: 783: unexpected token at 'require 'minitest/autorun'

class HelloTest < Minitest::Test
  def test_world
    assert_equal 'world', "world!", "Hello.world should return a string called 'world'"
  end

  def test_flunk
    flunk "You shall not pass"
  end
end'>
/Applications/SketchUp 2021/SketchUp.app/Contents/Frameworks/Ruby.framework/Versions/2.7.1/lib/ruby/2.7.0/json/common.rb:156:in `parse'
```
I have followed the steps mentioned [here](https://github.com/SketchUp/testup-2) to set up. Am I missing something here?

Note: I am able to run the tests by directly invoking minitest: `ruby -Ilib:test`
OS: macOS cataline
SketchUp: 2021 pro

**Comment by thomthom** [comment]
You cannot derive from `Minitest::Test` directly. To allow Minitest to function within SketchUp we had to wrap the base test class.

Have a look at this page: https://github.com/SketchUp/testup-2/wiki/Setting-up-test-suites

If it still doesn't work, can you post a .zip file with an example test suite that doesn't work? Along with a screenshot of how your Settings dialog looks like.

**Comment by anuragaj** [comment]
> You cannot derive from `Minitest::Test` directly. To allow Minitest to function within SketchUp we had to wrap the base test class.
> 
> Have a look at this page: https://github.com/SketchUp/testup-2/wiki/Setting-up-test-suites
> 
> If it still doesn't work, can you post a .zip file with an example test suite that doesn't work? Along with a screenshot of how your Settings dialog looks like.

My bad, the problem was with file name. It's supposed to start with TC_. The wiki you linked had it. It's now being discovered. Thank you.
