### ISSUE TITLE
Make TestUp compatible with SketchUp older than 2014

### ISSUE THREAD

**Issue by thomthom** [SketchUp/testup-2#85]
At the very least it would be nice to be able to run TestUp on SU2013, Ruby 1.8. This means repackaging some of the StdLibs for Ruby 1.8 that we use.

**Comment by DanRathbun** [comment]
FYI, reason: All SketchUp versions that run Ruby 1.8.x are out of active support.
Should anyone still wish to use TestUp on such old versions can manually try making the changes I show above and use the Ruby lib RBZ linked.

**Comment by thomthom** [comment]
That - and the effort is too high vs gain. Technically SU2014 is also out of support, but since the effort to allow TestUp to run on that version is so low it's worth it for the benefit of being able to check for potential regression history.
